<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DecoCategory.aspx.cs" Inherits="AuroraDecos.DecoCategory" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .auto-style1 {
            width: 347px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="navPlaceHolder" runat="server">

    <div id="divTblProduct" class="d-flex justify-content-center w-60">
        <div>
            <table id="tblProduct">

                <tr>
                    <td>
                        <h2 class="text-center subheadings">
                            <asp:Label ID="Label10" runat="server" Text="Deco Category" CssClass="text-success"></asp:Label>

                        </h2>
                    </td>
                </tr>

                <tr class="auto-style1">
                    <td>
                        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Id" DataSourceID="DecoCategoryDataSource" PageSize="5" CellPadding="4" ForeColor="#333333" GridLines="None" Height="357px" Width="819px">
                            <AlternatingRowStyle BackColor="White" />
                            <Columns>
                                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                                <asp:BoundField DataField="ImagePath" HeaderText="ImagePath" SortExpression="ImagePath" />
                                <asp:BoundField DataField="CategoryId" HeaderText="CategoryId" SortExpression="CategoryId" />
                            </Columns>
                            <EditRowStyle BackColor="#ccc8c0" />
                            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" VerticalAlign="Middle" HorizontalAlign="Center" />
                            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#E3EAEB" />
                            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#F8FAFA" />
                            <SortedAscendingHeaderStyle BackColor="#246B61" />
                            <SortedDescendingCellStyle BackColor="#D4DFE1" />
                            <SortedDescendingHeaderStyle BackColor="#15524A" />
                        </asp:GridView>
                        <asp:SqlDataSource ID="DecoCategoryDataSource" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:AuroraConnectionString %>" DeleteCommand="DELETE FROM [tblItemsCatgory] WHERE [Id] = @original_Id AND [Name] = @original_Name AND (([Description] = @original_Description) OR ([Description] IS NULL AND @original_Description IS NULL)) AND (([ImagePath] = @original_ImagePath) OR ([ImagePath] IS NULL AND @original_ImagePath IS NULL)) AND [CategoryId] = @original_CategoryId" InsertCommand="INSERT INTO [tblItemsCatgory] ([Name], [Description], [ImagePath], [CategoryId]) VALUES (@Name, @Description, @ImagePath, @CategoryId)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [tblItemsCatgory] ORDER BY [Name]" UpdateCommand="UPDATE [tblItemsCatgory] SET [Name] = @Name, [Description] = @Description, [ImagePath] = @ImagePath, [CategoryId] = @CategoryId WHERE [Id] = @original_Id AND [Name] = @original_Name AND (([Description] = @original_Description) OR ([Description] IS NULL AND @original_Description IS NULL)) AND (([ImagePath] = @original_ImagePath) OR ([ImagePath] IS NULL AND @original_ImagePath IS NULL)) AND [CategoryId] = @original_CategoryId">
                            <DeleteParameters>
                                <asp:Parameter Name="original_Id" Type="Int32" />
                                <asp:Parameter Name="original_Name" Type="String" />
                                <asp:Parameter Name="original_Description" Type="String" />
                                <asp:Parameter Name="original_ImagePath" Type="String" />
                                <asp:Parameter Name="original_CategoryId" Type="Int32" />
                            </DeleteParameters>
                            <InsertParameters>
                                <asp:Parameter Name="Name" Type="String" />
                                <asp:Parameter Name="Description" Type="String" />
                                <asp:Parameter Name="ImagePath" Type="String" />
                                <asp:Parameter Name="CategoryId" Type="Int32" />
                            </InsertParameters>
                            <UpdateParameters>
                                <asp:Parameter Name="Name" Type="String" />
                                <asp:Parameter Name="Description" Type="String" />
                                <asp:Parameter Name="ImagePath" Type="String" />
                                <asp:ControlParameter Name="CategoryId" ControlID="ddlLocation" PropertyName="SelectedValue" Type="Int32" />
                                <asp:Parameter Name="original_Id" Type="Int32" />
                                <asp:Parameter Name="original_Name" Type="String" />
                                <asp:Parameter Name="original_Description" Type="String" />
                                <asp:Parameter Name="original_ImagePath" Type="String" />
                                <asp:Parameter Name="original_CategoryId" Type="Int32" />
                            </UpdateParameters>
                        </asp:SqlDataSource>

                    </td>
                </tr>

                <tr>
                    <td>
                        <h3 class="text-center subheadingsIns">
                            <asp:Label ID="Label1" runat="server" Text="Add New Deco Categories"></asp:Label>
                        </h3>
                    </td>
                </tr>

                <tr>
                    <td class="mytd">
                        <formview>
                            <table id="tblDecoCate">
                                <tr>
                                    <td>
                                        <asp:Label ID="Label2" runat="server" Text="Deco Category Name"></asp:Label>
                                    </td>
                                    <td class="auto-style1">
                                        <asp:TextBox ID="txtDecoCategory" runat="server"></asp:TextBox>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <asp:Label ID="Label4" runat="server" Text="Description"></asp:Label>
                                    </td>
                                    <td class="auto-style1">
                                        <asp:TextBox ID="txtDescription" runat="server"></asp:TextBox>
                                    </td>
                                </tr>

                                <tr>
                                    <td>
                                        <asp:Label ID="Label5" runat="server" Text="Indoor/Outdoor"></asp:Label>
                                    </td>
                                    <td class="auto-style1">
                                        <asp:DropDownList ID="ddlLocation" runat="server" Height="37px" Width="345px" AutoPostBack="True" DataSourceID="CategoryDataSource" DataTextField="Description" DataValueField="Id">
                                        </asp:DropDownList>
                                        <asp:SqlDataSource ID="CategoryDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:AuroraConnectionString %>" SelectCommand="SELECT [Id], [Description] FROM [tblCategory]"></asp:SqlDataSource>
                                    </td>
                                </tr>

                                <tr class="btnTd">
                                    <td  colspan="2">
                                        <asp:Button ID="btnAddCategory" runat="server" CssClass="btn btn-success rounded-1 text-center" Text="Add New Deco Category" OnClick="btnAddCategory_Click" />
                                    </td>
                                </tr>
                            </table>
                        </formview>

                    </td>
                </tr>



            </table>

        </div>

    </div>

</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="footerPlaceHolder" runat="server">
</asp:Content>
